# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8222a86333f10256ddd3e157503a9f3b910e094e22faaea334aafad7529d610c07a3a93b0a88288ea6bb9f662441f4e340646d490d521ad813e7e15c6d12c118

test:
  secret_key_base: 5e4125ad199bf0937f026e2edf8bcafd7efbc7d0fb3585647fe27c8fe64baf8d660a6cc726817c39fc18b85087e1de665649e969c410ddcd246055c26f3aeeb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
